POST http://localhost:3005/api/users
Content-Type: application/json

{
    "email": "info@gmail.com",
    "username": "info",
    "name": "Test",
    "lastName": "Lastname test",
    "password": "123456"
}